networks:
  keycloak:

volumes:
  database:

services:
  postgres:
    image: postgres:16
    command: ["--max_prepared_transactions=110"]
    networks:
      - keycloak
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  keycloak:
    image: keycloak-custom:26.6.2
    build: keycloak-custom
    command: ["start-dev", "--transaction-xa-enabled=true"]
    networks:
      - keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HEALTH_ENABLED: true
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/9000 && echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 && cat <&3 | grep -q '\"status\": \"UP\"'"]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s

  keycloak-test:
    profiles:
      - test
    image: keycloak-test:26.6.2
    build: keycloak-test
    networks:
      - keycloak
    depends_on:
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "test -r /tmp/result && test \"$(cat /tmp/result)\" = succeeded"]
      interval: 5s
      timeout: 5s
      retries: 30

