# Settings specific to the keycloak-custom container in general

cache=local
db=postgres
db-url-host=postgres
db-url-database=postgres
transaction-xa-enabled=true
http-enabled=true
http-port=8080
hostname-strict=false
health-enabled=true

